"use client";

import { useEffect, useRef, useState } from "react";
import dynamic from "next/dynamic";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Boxes, Check, ChevronRight, Command, Copy, Crosshair, FileWarning, LockKeyhole, Network, NotebookPen, Search, ShieldCheck, Terminal, Workflow } from "lucide-react";
import { motion } from "motion/react";
import { Button } from "@/components/ui/button";
import { GraphFallback } from "@/components/landing/graph-fallback";
import { demoMode } from "@/lib/utils";

const HeroGraph = dynamic(() => import("@/components/landing/hero-graph").then(module => module.HeroGraph), { ssr: false, loading: () => <GraphFallback /> });
const command = "docker compose up -d";
const modules = [
  { id: "research", label: "Research", icon: NotebookPen, kicker: "KNOWLEDGE BASE", title: "Follow every thread.", description: "Write in Markdown, connect notes, and turn research into a finding without losing context.", rows: ["Authentication research", "SSRF methodology", "Target overview"] },
  { id: "findings", label: "Findings", icon: FileWarning, kicker: "REPORT LIFECYCLE", title: "From signal to report.", description: "Track severity, evidence, status, disclosures, and payouts in one structured record.", rows: ["Blind SSRF in webhook handler", "IDOR in invoice export", "Stored XSS in profile description"] },
  { id: "targets", label: "Targets", icon: Crosshair, kicker: "SCOPE INTELLIGENCE", title: "Know what is in scope.", description: "Organize programs, assets, and recon data so context is always one click away.", rows: ["Acme Cloud", "Northstar Commerce", "Open Source Research"] },
  { id: "operations", label: "Operations", icon: Workflow, kicker: "DAILY OPERATIONS", title: "Stay ahead of deadlines.", description: "Watch disclosure windows, audit activity, and keep the whole workflow moving.", rows: ["Disclosure watch", "Research activity", "CVE watchlist"] },
];
const capabilities = [
  { icon: NotebookPen, title: "Linked notes", body: "Markdown research with backlinks and a visual map of your ideas.", wide: true },
  { icon: FileWarning, title: "Finding lifecycle", body: "Draft, submit, triage, disclose, and track every outcome." },
  { icon: Network, title: "Asset intelligence", body: "Keep scope, services, and discoveries tied to each project." },
  { icon: ShieldCheck, title: "Disclosure watch", body: "See approaching deadlines before they become overdue." },
  { icon: Command, title: "Fast navigation", body: "Jump to any target, note, or command from the keyboard." },
  { icon: LockKeyhole, title: "Your infrastructure", body: "Self-host the workspace and control where research lives.", wide: true },
];

function DemoMock({ active }: { active: number }) {
  const item = modules[active];
  return <div className="overflow-hidden rounded-xl border border-strong bg-surface">
    <div className="flex h-10 items-center gap-2 border-b border-subtle bg-elevated px-4"><span className="h-2 w-2 rounded-full bg-sev-critical/70" /><span className="h-2 w-2 rounded-full bg-sev-medium/70" /><span className="h-2 w-2 rounded-full bg-accent/70" /><span className="ml-3 mono text-[10px] text-muted">skyvision / {item.id}</span></div>
    <div className="grid min-h-[310px] grid-cols-[58px_1fr]"><div className="space-y-3 border-r border-subtle p-4">{[Crosshair, NotebookPen, FileWarning, Network, Boxes].map((Icon,index) => <div key={index} className={"flex h-6 w-6 items-center justify-center rounded " + (index === active ? "bg-accent/15 text-accent" : "text-muted")}><Icon size={14} strokeWidth={1.5} /></div>)}</div><div className="p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-widest text-muted">{item.kicker}</p><h3 className="mt-1 font-semibold">{item.label}</h3></div><div className="rounded border border-subtle bg-elevated p-1.5 text-muted"><Search size={13} /></div></div><div className="space-y-2">{item.rows.map((row,index) => <div key={row} className="flex items-center gap-3 rounded-md border border-subtle bg-base px-3 py-3"><span className={"h-1.5 w-1.5 rounded-full " + (index === 0 ? "bg-accent" : index === 1 ? "bg-sev-medium" : "bg-sev-low")} /><span className="flex-1 text-[11px]">{row}</span><ChevronRight size={12} className="text-muted" /></div>)}</div><div className="mt-5 grid grid-cols-3 gap-2">{[1,2,3].map(index => <div key={index} className="h-12 rounded border border-subtle bg-elevated/40 p-2"><div className="mb-2 h-1 w-8 rounded bg-border-strong" /><div className="h-2 w-12 rounded bg-border-strong/60" /></div>)}</div></div></div>
  </div>;
}

export default function LandingPage() {
  const [scrolled, setScrolled] = useState(false);
  const [graphEnabled, setGraphEnabled] = useState(false);
  const [graphVisible, setGraphVisible] = useState(true);
  const [active, setActive] = useState(0);
  const [copied, setCopied] = useState(false);
  const heroRef = useRef<HTMLElement>(null);
  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 40);
    onScroll(); window.addEventListener("scroll", onScroll, { passive: true });
    setGraphEnabled(!window.matchMedia("(prefers-reduced-motion: reduce)").matches && !window.matchMedia("(max-width: 768px)").matches);
    const heroObserver = new IntersectionObserver(entries => setGraphVisible(entries[0]?.isIntersecting ?? false), { rootMargin: "50px" });
    if (heroRef.current) heroObserver.observe(heroRef.current);
    const moduleObserver = new IntersectionObserver(entries => {
      const visible = entries.filter(entry => entry.isIntersecting).sort((a,b) => b.intersectionRatio - a.intersectionRatio)[0];
      if (visible) setActive(Number((visible.target as HTMLElement).dataset.index));
    }, { rootMargin: "-25% 0px -35% 0px", threshold: [0, .25, .5, .75] });
    document.querySelectorAll("[data-module]").forEach(node => moduleObserver.observe(node));
    return () => { window.removeEventListener("scroll", onScroll); heroObserver.disconnect(); moduleObserver.disconnect(); };
  }, []);
  async function copy() { await navigator.clipboard.writeText(command); setCopied(true); window.setTimeout(() => setCopied(false), 1600); }
  return <div className="min-h-screen bg-base">
    <header className={"fixed inset-x-0 top-0 z-40 border-b transition-all " + (scrolled ? "border-subtle bg-base/90 backdrop-blur-md" : "border-transparent bg-transparent")}><nav className="mx-auto flex h-16 max-w-[1380px] items-center justify-between px-6 lg:px-10"><Link href="/" className="mono text-[18px] font-semibold tracking-[-.065em]">skyvision<span className="text-accent">.</span></Link><div className="hidden items-center gap-8 text-secondary md:flex"><a href="#features" className="hover:text-primary">Features</a><a href="#modules" className="hover:text-primary">Modules</a><a href="#self-host" className="hover:text-primary">Self-host</a><a href="https://github.com" className="hover:text-primary">GitHub <ArrowUpRight size={12} className="inline" /></a></div><div className="flex items-center gap-2"><Link href="/login"><Button variant="ghost" size="sm" className="hidden sm:inline-flex">Sign in</Button></Link><Link href={demoMode ? "/dashboard" : "/signup"}><Button variant="primary" size="sm">{demoMode ? "Open demo" : "Get started"} <ArrowRight size={14} /></Button></Link></div></nav></header>
    <section ref={heroRef} className="relative mx-auto flex min-h-[780px] max-w-[1380px] items-center overflow-hidden px-6 pb-20 pt-32 lg:px-10"><div className="pointer-events-none absolute inset-y-0 right-[-12%] w-[72%] opacity-80 max-md:right-[-30%] max-md:w-[100%] max-md:opacity-30">{graphEnabled && graphVisible ? <HeroGraph /> : <GraphFallback />}</div><div className="relative z-10 max-w-[700px]"><motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .5 }}><span className="eyebrow inline-flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-accent" /> YOUR RESEARCH, CONNECTED</span><h1 className="display mt-7">One place for<br /><span className="text-accent">every signal.</span></h1><p className="mt-7 max-w-[550px] text-[16px] leading-7 text-secondary">Run your entire security research workflow from one focused workspace. Capture leads, map targets, build reports, and keep disclosure on track.</p><div className="mt-9 flex flex-wrap gap-3"><Link href={demoMode ? "/dashboard" : "/signup"}><Button variant="primary" className="h-10 px-5">Explore the workspace <ArrowRight size={16} /></Button></Link><a href="#modules"><Button className="h-10 px-5">See how it works <ChevronRight size={16} /></Button></a></div><div className="mt-14 max-w-[465px] overflow-hidden rounded-lg border border-subtle bg-surface/95"><div className="flex items-center justify-between border-b border-subtle px-4 py-2 text-[10px] uppercase tracking-widest text-muted"><span>Self-host in one command</span><Terminal size={14} /></div><div className="flex items-center justify-between gap-4 px-4 py-3"><code className="mono text-[12px] text-accent">$ {command}</code><button type="button" onClick={() => void copy()} aria-label="Copy Docker command" className="text-muted hover:text-primary">{copied ? <Check size={15} /> : <Copy size={15} />}</button></div></div></motion.div></div><div className="absolute bottom-8 left-10 flex items-center gap-3 text-[10px] uppercase tracking-widest text-muted"><span className="h-6 w-px bg-border-strong" />Scroll to explore</div></section>
    <section id="modules" className="border-y border-subtle bg-surface/40 py-24"><div className="mx-auto max-w-[1380px] px-6 lg:px-10"><p className="eyebrow">BUILT FOR THE WHOLE WORKFLOW</p><h2 className="mb-14 mt-4 max-w-xl text-4xl font-semibold leading-tight tracking-[-.045em]">Keep context from first lead to final disclosure.</h2><div className="grid gap-12 lg:grid-cols-[minmax(0,.9fr)_minmax(0,1.1fr)]"><div>{modules.map((item,index) => <article key={item.id} data-module data-index={index} className={"flex min-h-[260px] scroll-mt-28 gap-5 border-l-2 py-7 pl-6 transition-colors " + (active === index ? "border-accent" : "border-subtle")}><div className={"flex h-9 w-9 shrink-0 items-center justify-center rounded-md border " + (active === index ? "border-accent/30 bg-accent/10 text-accent" : "border-subtle text-muted")}><item.icon size={18} strokeWidth={1.5} /></div><div><span className="eyebrow">{item.kicker}</span><h3 className="mt-3 text-2xl font-semibold tracking-tight">{item.title}</h3><p className="mt-3 max-w-sm text-secondary">{item.description}</p></div></article>)}</div><div className="sticky top-28 h-fit"><DemoMock active={active} /><p className="mt-3 text-right mono text-[10px] text-muted">0{active + 1} / 0{modules.length}</p></div></div></div></section>
    <section id="features" className="mx-auto max-w-[1380px] px-6 py-28 lg:px-10"><p className="eyebrow">CAPABILITIES</p><div className="mb-12 flex flex-wrap items-end justify-between gap-4"><h2 className="mt-4 max-w-[600px] text-4xl font-semibold leading-tight tracking-[-.045em]">Every tool you need.<br />None of the noise.</h2><p className="max-w-xs text-secondary">Designed for researchers who need their tools to keep up with their thinking.</p></div><div className="grid gap-4 md:grid-cols-4">{capabilities.map(item => <div key={item.title} className={"panel min-h-52 p-6 transition-transform duration-200 hover:-translate-y-0.5 hover:border-strong " + (item.wide ? "md:col-span-2" : "")}><div className="mb-9 flex h-9 w-9 items-center justify-center rounded-md border border-accent/25 bg-accent/10 text-accent"><item.icon size={18} strokeWidth={1.5} /></div><h3 className="text-base font-semibold">{item.title}</h3><p className="mt-2 max-w-sm text-secondary">{item.body}</p></div>)}</div></section>
    <section id="self-host" className="border-t border-subtle bg-surface/30 py-28"><div className="mx-auto max-w-[1380px] px-6 lg:px-10"><div className="grid gap-12 lg:grid-cols-2"><div><p className="eyebrow">OWN YOUR WORKSPACE</p><h2 className="mt-4 text-4xl font-semibold leading-tight tracking-[-.045em]">Your research stays<br />on your infrastructure.</h2><p className="mt-5 max-w-md text-secondary">Deploy the stack where you work. Keep notes, findings, secrets, and audit history under your control.</p><Link href={demoMode ? "/dashboard" : "/signup"} className="mt-7 inline-flex items-center gap-2 text-accent">Explore SkyVision <ArrowRight size={15} /></Link></div><div className="space-y-3">{[["01","Clone the repository","git clone your-skyvision-repo"],["02","Configure your environment","cp .env.example .env"],["03","Start the stack",command]].map(([step,title,code]) => <div key={step} className="panel flex items-start gap-4 p-4"><span className="mono text-accent">{step}</span><div><h3 className="font-medium">{title}</h3><code className="mono mt-2 block text-[11px] text-muted">{code}</code></div></div>)}</div></div></div></section>
    <footer className="border-t border-subtle"><div className="mx-auto flex max-w-[1380px] flex-wrap items-center justify-between gap-4 px-6 py-10 text-secondary lg:px-10"><span className="mono text-[16px] font-semibold text-primary">skyvision<span className="text-accent">.</span></span><span>Research with clarity. Disclose with confidence.</span><span className="text-[11px]">© {new Date().getFullYear()} SkyVision</span></div></footer>
  </div>;
}
